CFLAGS=-Wall -g

ex17: ex17.c
	cc $(CFLAGS) ex17.c -o ex17

ex17_additional: ex17_additional.c
	cc $(CFLAGS) ex17_additional.c -o ex17_additional

.PHONY: clean
clean:
	rm -f ./ex17 ./ex17_additional ./core* ./vgcore* db*
